---
# tasks file for selina
- name: Install the latest version of libselinux-python3
  ansible.builtin.yum:
    name: 
      - libselinux-python3
    state: latest
  tags: 
    - selina

- name: Copy config
  copy: 
    src: config
    dest: /etc/selinux/config
    owner: root
    group: root
  notify:
    - Reboot machine
  tags: 
    - selina
